version: '3'
services:
  usb-reset:
    build:
      context: .
      dockerfile: Dockerfile
    image: zdziebek/usb-reset:latest
    restart: unless-stopped
    volumes:
      - /sys:/sys:rw
      - /dev:/dev:rw
    privileged: true
